server:
  port: 8888
spring:
  application:
    name: im-platform
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/lckf?useUnicode=true&characterEncoding=utf8&noAccessToProcedureBodies=true&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#    username: lckf
#    password: P5b6nknrBzNSW7SH
    url: jdbc:mysql://localhost:3306/boxim?useUnicode=true&characterEncoding=utf8&noAccessToProcedureBodies=true&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: boxim
    password: 123456
  redis:
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: 123456
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  mapper-locations:
    - classpath*:mapper/*.xml
minio:
#  endpoint: http://127.0.0.1:9090
#  public: http://43.132.126.240:9090
  #  public: http://43.129.82.76:9090
#  public: http://43.132.168.72:9090
#  endpoint: http://127.0.0.1:9090
#  public: http://47.57.188.97:9090
  endpoint: http://127.0.0.1:9090
  public: https://ngbt.qdcspy.shop/file
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: box-im
  imagePath: image
  filePath: file
  videoPath: video
webrtc:
  iceServers: #coturn配置
    - urls: stun:www.boxim.online:3478
      username: admin
      credential: UrHHKNvE7nFvBTMV
    - urls: turn:www.boxim.online:3478
      username: admin
      credential: UrHHKNvE7nFvBTMV
jwt:
  accessToken:
    expireIn: 86400  #1天
    secret: ztcv8qKGHV
  refreshToken:
    expireIn: 604800 #7天
    secret: g2VnugZYLw
logging:
  config: classpath:logback-prod.xml
ip:
  url: http://ip-api.com/json/